server:
  port: 8080
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema:
    - classpath:schema.sql
    data:
    - classpath:data.sql
  application:
    name: spring-cloud-micro-provider-user
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.ja0ck5: debug
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://ja0ck5:jack123@localhost:8761/eureka,http://ja0ck5:jack123@localhost:8762/eureka,http://ja0ck5:jack123@localhost:8763/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    metadata-map:
      zone: ja0ck5
      who: whoAmI
    lease-renewal-interval-in-seconds: 5
    appname: spring-cloud-micro-provider-user