# security
security:
  basic:
    enabled: true
  user:
    name: ja0ck5
    password: jack123

server:
  port: 8096
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://ja0ck5:jack123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}


spring:
  application:
      name: spring-cloud-micro-config-security
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ja0ck5/spring-cloud-custom-config # ¹«ÓÃ