# security
security:
  basic:
    enabled: true
  user:
    name: ja0ck5
    password: jack123

server:
  port: 8761
eureka:
  client:
    # EurekaDiscoveryClientConfiguration 源码中可以找到配置。ide 没有提示
    healthcheck:
      enabled: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://ja0ck5:jack123@localhost:8761/eureka
    # server
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}} #${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  datacenter: cloud # spring cloud 并没有说明，需要去 github 上面找
  environment: prod # spring cloud 并没有说明，需要去 github 上面找