
server:
  port: 8089
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://ja0ck5:jack123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
spring:
  application:
    name: spring-cloud-micro-gateway-zuul

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

